"""Add email confirmation fields to user

Revision ID: b7903c245945
Revises: 57b190cb183b
Create Date: 2026-05-18 16:30:08.116954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'b7903c245945'
down_revision: Union[str, None] = '57b190cb183b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_model', sa.Column('is_email_confirmed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_model', sa.Column('email_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_model', 'email_confirmed_at')
    op.drop_column('user_model', 'is_email_confirmed')
    # ### end Alembic commands ###
